//! Partially auto-generated.

const std = @import("std");
const slurm = @import("root.zig");

pub extern fn slurm_free_node_info_members(node: *slurm.Node) void;
pub extern fn slurm_free_job_info_members(job: *slurm.Job) void;
pub extern fn slurm_free_shares_response_msg(msg: ?*slurm.db.Association.Shares.LoadResponse) void;
pub extern fn slurm_free_stats_response_msg(msg: ?*slurm.slurmctld.Statistics) void;
pub extern fn gid_to_string_or_null(gid: std.c.gid_t) ?slurm.CStr;

pub extern fn slurm_strerror(errnum: c_int) ?slurm.CStr;
pub extern fn slurm_seterrno(errnum: c_int) void;
pub extern fn slurm_perror(msg: ?slurm.CStr) void;
pub extern fn slurm_init(conf: ?*u8) void;
pub extern fn slurm_fini() void;
pub extern fn slurm_get_cluster_info(cluster_records: *?*slurm.List(*anyopaque), cluster_names: ?slurm.CStr, show_flags: u16) c_int;
pub extern fn slurm_init_job_desc_msg(job_desc_msg: ?*slurm.JobSubmitDescription) void;
pub extern fn slurm_allocate_resources(job_desc_msg: ?*slurm.JobSubmitDescription, job_alloc_resp_msg: *?*slurm.JobSubmitDescription.AllocationResponse) c_int;
pub extern fn slurm_free_resource_allocation_response_msg(msg: ?*slurm.JobSubmitDescription.AllocationResponse) void;
pub extern fn slurm_allocation_lookup(job_id: u32, resp: *?*slurm.JobSubmitDescription.AllocationResponse) c_int;
pub extern fn slurm_het_job_lookup(jobid: u32, resp: *?*slurm.List(*anyopaque)) c_int;
pub extern fn slurm_read_hostfile(filename: ?*u8, n: c_int) ?slurm.CStr;
pub extern fn slurm_submit_batch_job(job_desc_msg: ?*slurm.JobSubmitDescription, slurm_alloc_msg: *?*slurm.JobSubmitDescription.Response) c_int;
pub extern fn slurm_submit_batch_het_job(job_req_list: ?*slurm.List(*anyopaque), slurm_alloc_msg: *?*slurm.JobSubmitDescription.Response) c_int;
pub extern fn slurm_free_submit_response_response_msg(msg: ?*slurm.JobSubmitDescription.Response) void;
pub extern fn slurm_job_will_run(job_desc_msg: ?*slurm.JobSubmitDescription) c_int;
pub extern fn slurm_het_job_will_run(job_req_list: ?*slurm.List(*anyopaque)) c_int;
pub extern fn slurm_sort_will_run_resp(a: ?*anyopaque, b: ?*anyopaque) c_int;
pub extern fn slurm_load_licenses(arg0: std.posix.time_t, arg1: *?*slurm.License.LoadResponse, arg2: u16) c_int;
pub extern fn slurm_free_license_info_msg(arg0: ?*slurm.License.LoadResponse) void;
pub extern fn slurm_kill_job(job_id: u32, signal: u16, flags: slurm.job.SignalFlags) c_int;
pub extern fn slurm_kill_job_step(step_id: ?*slurm.Step.ID, signal: u16, flags: u16) c_int;
pub extern fn slurm_kill_job2(job_id: ?*u8, signal: u16, flags: u16, sibling: ?*u8) c_int;
pub extern fn slurm_signal_job(job_id: u32, signal: u16) c_int;
pub extern fn slurm_signal_job_step(step_id: ?*slurm.Step.ID, signal: u32) c_int;
pub extern fn slurm_complete_job(step_id: ?*slurm.Step.ID, job_return_code: u32) c_int;
pub extern fn slurm_terminate_job_step(step_id: ?*slurm.Step.ID) c_int;
pub extern fn slurm_step_launch_wait_start(ctx: ?*slurm.StepCtx) c_int;
pub extern fn slurm_step_launch_wait_finish(ctx: ?*slurm.StepCtx) void;
pub extern fn slurm_step_launch_abort(ctx: ?*slurm.StepCtx) void;
pub extern fn slurm_step_launch_fwd_signal(ctx: ?*slurm.StepCtx, signo: c_int) void;
pub extern fn slurm_step_launch_fwd_wake(ctx: ?*slurm.StepCtx) void;
pub extern fn slurm_api_version() c_long;
pub extern fn slurm_load_ctl_conf(update_time: std.posix.time_t, slurm_ctl_conf_ptr: *?*slurm.slurmctld.Config) c_int;
pub extern fn slurm_free_ctl_conf(slurm_ctl_conf_ptr: ?*slurm.slurmctld.Config) void;
pub extern fn slurm_write_ctl_conf(slurm_ctl_conf_ptr: ?*slurm.slurmctld.Config, node_info_ptr: ?*slurm.Node.LoadResponse, part_info_ptr: ?*slurm.Partition.LoadResponse) void;
pub extern fn slurm_ctl_conf_2_key_pairs(slurm_ctl_conf_ptr: ?*slurm.slurmctld.Config) ?*anyopaque;
pub extern fn slurm_init_update_step_msg(step_msg: ?*slurm.Step.Updatable) void;
pub extern fn slurm_get_statistics(buf: *?*slurm.slurmctld.Statistics, req: ?*slurm.slurmctld.Statistics.Request) c_int;
pub extern fn slurm_reset_statistics(req: ?*slurm.slurmctld.Statistics.Request) c_int;
pub extern fn slurm_get_resource_layout(step_id: ?*slurm.Step.ID, response: *?*anyopaque) c_int;
pub extern fn slurm_free_job_info_msg(job_buffer_ptr: ?*slurm.Job.LoadResponse) void;
pub extern fn slurm_get_end_time(jobid: u32, end_time_ptr: ?*std.posix.time_t) c_int;
pub extern fn slurm_get_job_stderr(buf: ?slurm.CStr, buf_size: c_int, job_ptr: ?*slurm.Job) void;
pub extern fn slurm_get_job_stdin(buf: ?slurm.CStr, buf_size: c_int, job_ptr: ?*slurm.Job) void;
pub extern fn slurm_get_job_stdout(buf: ?slurm.CStr, buf_size: c_int, job_ptr: ?*slurm.Job) void;
pub extern fn slurm_expand_step_stdio_fields(path: ?slurm.CStr, step: ?*slurm.Step) ?slurm.CStr;
pub extern fn slurm_expand_job_stdio_fields(path: ?slurm.CStr, job: ?*slurm.Job) ?slurm.CStr;
pub extern fn slurm_get_rem_time(jobid: u32) c_long;
pub extern fn slurm_job_node_ready(job_id: u32) c_int;
pub extern fn slurm_load_job(resp: *?*slurm.Job.LoadResponse, job_id: u32, show_flags: slurm.ShowFlags) c_int;
pub extern fn slurm_load_job_user(job_info_msg_pptr: *?*slurm.Job.LoadResponse, user_id: u32, show_flags: u16) c_int;
pub extern fn slurm_load_jobs(update_time: std.posix.time_t, job_info_msg_pptr: *?*slurm.Job.LoadResponse, show_flags: slurm.ShowFlags) c_int;
pub extern fn slurm_notify_job(job_id: u32, message: ?slurm.CStr) c_int;
pub extern fn slurm_pid2jobid(job_pid: std.posix.pid_t, job_id_ptr: ?[*]u32) c_int;
pub extern fn slurm_update_job(job_msg: ?*slurm.JobSubmitDescription) c_int;
pub extern fn slurm_get_job_steps(step_id: ?*slurm.Step.ID, resp: *?*slurm.Step.LoadResponse, show_flags: slurm.ShowFlags) c_int;
pub extern fn slurm_find_step_ids_by_container_id(show_flags: u16, uid: std.posix.uid_t, container_id: ?*u8, steps: ?*slurm.List(*anyopaque)) c_int;
pub extern fn slurm_free_job_step_info_response_msg(msg: ?*slurm.Step.LoadResponse) void;
pub extern fn slurm_job_step_pids_response_msg_free(object: ?*anyopaque) void;
pub extern fn slurm_job_step_stat_response_msg_free(object: ?*anyopaque) void;
pub extern fn slurm_update_step(step_msg: ?*slurm.Step.Updatable) c_int;
pub extern fn slurm_destroy_selected_step(object: ?*anyopaque) void;
pub extern fn slurm_load_node(update_time: std.posix.time_t, resp: *?*slurm.Node.LoadResponse, show_flags: slurm.ShowFlags) c_int;
pub extern fn slurm_load_node2(update_time: std.posix.time_t, resp: *?*slurm.Node.LoadResponse, show_flags: u16, cluster: ?*slurm.db.Cluster) c_int;
pub extern fn slurm_load_node_single(resp: *?*slurm.Node.LoadResponse, node_name: ?slurm.CStr, show_flags: slurm.ShowFlags) c_int;
pub extern fn slurm_load_node_single2(resp: *?*slurm.Node.LoadResponse, node_name: ?slurm.CStr, show_flags: u16, cluster: ?*slurm.db.Cluster) c_int;
pub extern fn slurm_populate_node_partitions(node_buffer_ptr: ?*slurm.Node.LoadResponse, part_buffer_ptr: ?*slurm.Partition.LoadResponse) void;
pub extern fn slurm_get_node_energy(host: ?slurm.CStr, context_id: u16, delta: u16, sensors_cnt: ?[*]u16, energy: *?*slurm.AccountingGatherEnergy) c_int;
pub extern fn slurm_controller_hostlist_expansion(hostlist: ?*u8, expanded: ?[*]?slurm.CStr) c_int;
pub extern fn slurm_free_node_info_msg(node_buffer_ptr: ?*slurm.Node.LoadResponse) void;
pub extern fn slurm_sprint_node_table(node_ptr: ?*slurm.Node, one_liner: c_int) ?slurm.CStr;
pub extern fn slurm_init_update_node_msg(update_node_msg: ?*slurm.Node.Updatable) void;
pub extern fn slurm_create_node(node_msg: ?*slurm.Node.Updatable) c_int;
pub extern fn slurm_update_node(node_msg: ?*slurm.Node.Updatable) c_int;
pub extern fn slurm_delete_node(node_msg: ?*slurm.Node.Updatable) c_int;
pub extern fn slurm_init_part_desc_msg(update_part_msg: ?*slurm.Partition) void;
pub extern fn slurm_load_partitions(update_time: std.posix.time_t, part_buffer_ptr: *?*slurm.Partition.LoadResponse, show_flags: slurm.ShowFlags) c_int;
pub extern fn slurm_load_partitions2(update_time: std.posix.time_t, resp: *?*slurm.Partition.LoadResponse, show_flags: u16, cluster: ?*slurm.db.Cluster) c_int;
pub extern fn slurm_free_partition_info_msg(part_info_ptr: ?*slurm.Partition.LoadResponse) void;
pub extern fn slurm_sprint_partition_info(part_ptr: ?*slurm.Partition, one_liner: c_int) ?slurm.CStr;
pub extern fn slurm_create_partition(part_msg: ?*slurm.Partition) c_int;
pub extern fn slurm_update_partition(part_msg: ?*slurm.Partition) c_int;
pub extern fn slurm_delete_partition(part_msg: ?*slurm.Partition.DeleteFilter) c_int;
pub extern fn slurm_init_resv_desc_msg(update_resv_msg: ?*slurm.Reservation.Updatable) void;
pub extern fn slurm_create_reservation(resv_msg: ?*slurm.Reservation.Updatable) ?slurm.CStr;
pub extern fn slurm_update_reservation(resv_msg: ?*slurm.Reservation.Updatable) c_int;
pub extern fn slurm_delete_reservation(resv_msg: ?*slurm.Reservation.DeleteFilter) c_int;
pub extern fn slurm_load_reservations(update_time: std.posix.time_t, resp: *?*slurm.Reservation.LoadResponse) c_int;
pub extern fn slurm_sprint_reservation_info(resv_ptr: ?*slurm.Reservation, one_liner: c_int) ?slurm.CStr;
pub extern fn slurm_free_reservation_info_msg(resv_info_ptr: ?*slurm.Reservation.LoadResponse) void;
pub extern fn slurm_ping(dest: c_int) c_int;
pub extern fn slurm_reconfigure() c_int;
pub extern fn slurm_shutdown(options: u16) c_int;
pub extern fn slurm_takeover(backup_inx: c_int) c_int;
pub extern fn slurm_set_debugflags(debug_flags_plus: u64, debug_flags_minus: u64) c_int;
pub extern fn slurm_set_slurmd_debug_flags(node_list: ?slurm.CStr, debug_flags_plus: u64, debug_flags_minus: u64) c_int;
pub extern fn slurm_set_slurmd_debug_level(node_list: ?slurm.CStr, debug_level: u32) c_int;
pub extern fn slurm_set_debug_level(debug_level: u32) c_int;
pub extern fn slurm_set_schedlog_level(schedlog_level: u32) c_int;
pub extern fn slurm_set_fs_dampeningfactor(factor: u16) c_int;
pub extern fn slurm_suspend(job_id: u32) c_int;
pub extern fn slurm_resume(job_id: u32) c_int;
pub extern fn slurm_requeue(job_id: u32, flags: slurm.Job.State) c_int;
pub extern fn slurm_set_trigger(trigger_set: ?*slurm.Trigger) c_int;
pub extern fn slurm_clear_trigger(trigger_clear: ?*slurm.Trigger) c_int;
pub extern fn slurm_get_triggers(trigger_get: *?*slurm.Trigger.LoadResponse) c_int;
pub extern fn slurm_pull_trigger(trigger_pull: ?*slurm.Trigger) c_int;
pub extern fn slurm_free_trigger_msg(trigger_free: ?*slurm.Trigger.LoadResponse) void;
pub extern fn slurm_init_trigger_msg(trigger_info_msg: ?*slurm.Trigger) void;
pub extern fn slurm_burst_buffer_state_string(state: u16) ?slurm.CStr;
pub extern fn slurm_load_burst_buffer_stat(argc: c_int, argv: ?[*]?slurm.CStr, status_resp: ?[*]?slurm.CStr) c_int;
pub extern fn slurm_load_burst_buffer_info(burst_buffer_info_msg_pptr: *?*slurm.BurstBuffer.LoadResponse) c_int;
pub extern fn slurm_free_burst_buffer_info_msg(burst_buffer_info_msg: ?*slurm.BurstBuffer.LoadResponse) void;
pub extern fn slurm_top_job(job_id_str: ?slurm.CStr) c_int;
pub extern fn slurm_fetch_token(username: ?slurm.CStr, lifespan: c_int) ?slurm.CStr;
pub extern fn slurm_load_federation(fed_pptr: *?*anyopaque) c_int;
pub extern fn slurm_destroy_federation_rec(fed: ?*anyopaque) void;
pub extern fn slurm_request_crontab(uid: std.posix.uid_t, crontab: ?[*]?slurm.CStr, disabled_lines: ?[*]?slurm.CStr) c_int;
pub extern fn slurm_remove_crontab(uid: std.posix.uid_t, gid: std.posix.gid_t) c_int;
pub extern fn slurmdb_accounts_add(db_conn: ?*slurm.db.Connection, acct_list: ?*slurm.List(*anyopaque)) c_int;
pub extern fn slurmdb_accounts_add_cond(db_conn: ?*slurm.db.Connection, add_assoc: ?*slurm.db.Association.AddConditions, acct: ?*slurm.db.Account) ?slurm.CStr;
pub extern fn slurmdb_accounts_get(db_conn: ?*slurm.db.Connection, acct_cond: ?*slurm.db.Account.Filter) ?*slurm.List(*slurm.db.Account);
pub extern fn slurmdb_accounts_modify(db_conn: ?*slurm.db.Connection, acct_cond: ?*slurm.db.Account.Filter, acct: ?*slurm.db.Account) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_accounts_remove(db_conn: ?*slurm.db.Connection, acct_cond: ?*slurm.db.Account.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_archive(db_conn: ?*slurm.db.Connection, arch_cond: ?*slurm.db.Archive.Filter) c_int;
pub extern fn slurmdb_archive_load(db_conn: ?*slurm.db.Connection, arch_rec: ?*slurm.db.Archive) c_int;
pub extern fn slurmdb_associations_add(db_conn: ?*slurm.db.Connection, assoc_list: ?*slurm.List(*anyopaque)) c_int;
pub extern fn slurmdb_associations_get(db_conn: ?*slurm.db.Connection, assoc_cond: ?*slurm.db.Association.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_associations_modify(db_conn: ?*slurm.db.Connection, assoc_cond: ?*slurm.db.Association.Filter, assoc: ?*slurm.db.Association) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_associations_remove(db_conn: ?*slurm.db.Connection, assoc_cond: ?*slurm.db.Association.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_clusters_add(db_conn: ?*slurm.db.Connection, cluster_list: ?*slurm.List(*anyopaque)) c_int;
pub extern fn slurmdb_clusters_get(db_conn: ?*slurm.db.Connection, cluster_cond: ?*slurm.db.Cluster.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_clusters_modify(db_conn: ?*slurm.db.Connection, cluster_cond: ?*slurm.db.Cluster.Filter, cluster: ?*slurm.db.Cluster) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_clusters_remove(db_conn: ?*slurm.db.Connection, cluster_cond: ?*slurm.db.Cluster.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_report_cluster_account_by_user(db_conn: ?*slurm.db.Connection, assoc_cond: ?*slurm.db.Association.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_report_cluster_user_by_account(db_conn: ?*slurm.db.Connection, assoc_cond: ?*slurm.db.Association.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_report_cluster_wckey_by_user(db_conn: ?*slurm.db.Connection, wckey_cond: ?*slurm.db.WCKey.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_report_cluster_user_by_wckey(db_conn: ?*slurm.db.Connection, wckey_cond: ?*slurm.db.WCKey.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_report_job_sizes_grouped_by_account(db_conn: ?*slurm.db.Connection, job_cond: ?*slurm.db.Job.Filter, grouping_list: ?*slurm.List(*anyopaque), flat_view: bool, acct_as_parent: bool) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_report_job_sizes_grouped_by_wckey(db_conn: ?*slurm.db.Connection, job_cond: ?*slurm.db.Job.Filter, grouping_list: ?*slurm.List(*anyopaque)) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_report_job_sizes_grouped_by_account_then_wckey(db_conn: ?*slurm.db.Connection, job_cond: ?*slurm.db.Job.Filter, grouping_list: ?*slurm.List(*anyopaque), flat_view: bool, acct_as_parent: bool) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_report_user_top_usage(db_conn: ?*slurm.db.Connection, user_cond: ?*slurm.db.User.Filter, group_accounts: bool) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_connection_get(persist_conn_flags: ?[*]u16) ?*anyopaque;
pub extern fn slurmdb_connection_close(db_conn: ?*slurm.db.Connection) c_int;
pub extern fn slurmdb_connection_commit(db_conn: ?*slurm.db.Connection, commit: bool) c_int;
pub extern fn slurmdb_coord_add(db_conn: ?*slurm.db.Connection, acct_list: ?*slurm.List(*anyopaque), user_cond: ?*slurm.db.User.Filter) c_int;
pub extern fn slurmdb_coord_remove(db_conn: ?*slurm.db.Connection, acct_list: ?*slurm.List(*anyopaque), user_cond: ?*slurm.db.User.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_federations_add(db_conn: ?*slurm.db.Connection, federation_list: ?*slurm.List(*anyopaque)) c_int;
pub extern fn slurmdb_federations_modify(db_conn: ?*slurm.db.Connection, fed_cond: ?*slurm.db.Federation.Filter, fed: ?*slurm.db.Federation) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_federations_remove(db_conn: ?*slurm.db.Connection, fed_cond: ?*slurm.db.Federation.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_federations_get(db_conn: ?*slurm.db.Connection, fed_cond: ?*slurm.db.Federation.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_job_modify(db_conn: ?*slurm.db.Connection, job_cond: ?*slurm.db.Job.Filter, job: ?*slurm.db.Job) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_jobs_get(db_conn: ?*slurm.db.Connection, job_cond: ?*slurm.db.Job.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_jobs_fix_runaway(db_conn: ?*slurm.db.Connection, jobs: ?*slurm.List(*anyopaque)) c_int;
pub extern fn slurmdb_jobcomp_init() c_int;
pub extern fn slurmdb_jobcomp_fini() c_int;
pub extern fn slurmdb_jobcomp_jobs_get(job_cond: ?*slurm.db.Job.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_reconfig(db_conn: ?*slurm.db.Connection) c_int;
pub extern fn slurmdb_shutdown(db_conn: ?*slurm.db.Connection) c_int;
pub extern fn slurmdb_clear_stats(db_conn: ?*slurm.db.Connection) c_int;
pub extern fn slurmdb_config_get(db_conn: ?*slurm.db.Connection) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_events_get(db_conn: ?*slurm.db.Connection, event_cond: ?*slurm.db.Event.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_instances_get(db_conn: ?*slurm.db.Connection, instance_cond: ?*slurm.db.Instance.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_problems_get(db_conn: ?*slurm.db.Connection, assoc_cond: ?*slurm.db.Association.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_reservations_get(db_conn: ?*slurm.db.Connection, resv_cond: ?*slurm.db.Reservation.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_txn_get(db_conn: ?*slurm.db.Connection, txn_cond: ?*slurm.db.Transaction.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_get_info_cluster(cluster_names: ?slurm.CStr) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_get_first_avail_cluster(req: ?*slurm.JobSubmitDescription, cluster_names: ?slurm.CStr, cluster_rec: *?*slurm.db.Cluster) c_int;
pub extern fn slurmdb_get_first_het_job_cluster(job_req_list: ?*slurm.List(*anyopaque), cluster_names: ?slurm.CStr, cluster_rec: *?*slurm.db.Cluster) c_int;
pub extern fn slurmdb_destroy_assoc_usage(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_bf_usage(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_bf_usage_members(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_qos_usage(object: ?*anyopaque) void;
pub extern fn slurmdb_free_user_rec_members(slurmdb_user: ?*slurm.db.User) void;
pub extern fn slurmdb_destroy_user_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_account_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_coord_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_clus_res_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_cluster_accounting_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_cluster_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_federation_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_accounting_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_free_assoc_mgr_state_msg(object: ?*anyopaque) void;
pub extern fn slurmdb_free_assoc_rec_members(assoc: ?*slurm.db.Association) void;
pub extern fn slurmdb_destroy_assoc_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_event_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_instance_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_job_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_free_qos_rec_members(qos: ?*slurm.db.QoS) void;
pub extern fn slurmdb_destroy_qos_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_reservation_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_step_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_res_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_txn_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_wckey_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_archive_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_tres_rec_noalloc(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_tres_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_report_assoc_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_report_user_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_report_cluster_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_user_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_account_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_cluster_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_federation_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_tres_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_assoc_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_event_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_instance_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_job_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_job_cond_members(job_cond: ?*slurm.db.Job.Filter) void;
pub extern fn slurmdb_destroy_qos_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_reservation_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_res_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_txn_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_wckey_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_archive_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_free_add_assoc_cond_members(add_assoc: ?*slurm.db.Association.AddConditions) void;
pub extern fn slurmdb_destroy_add_assoc_cond(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_update_object(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_used_limits(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_print_tree(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_hierarchical_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_report_job_grouping(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_report_acct_grouping(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_report_cluster_grouping(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_rpc_obj(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_rollup_stats(object: ?*anyopaque) void;
pub extern fn slurmdb_free_stats_rec_members(object: ?*anyopaque) void;
pub extern fn slurmdb_destroy_stats_rec(object: ?*anyopaque) void;
pub extern fn slurmdb_free_slurmdb_stats_members(stats: ?*slurm.db.Step.Stats) void;
pub extern fn slurmdb_destroy_slurmdb_stats(stats: ?*slurm.db.Step.Stats) void;
pub extern fn slurmdb_init_assoc_rec(assoc: ?*slurm.db.Association, free_it: bool) void;
pub extern fn slurmdb_init_clus_res_rec(clus_res: ?*slurm.db.Resource.Cluster, free_it: bool) void;
pub extern fn slurmdb_init_cluster_rec(cluster: ?*slurm.db.Cluster, free_it: bool) void;
pub extern fn slurmdb_init_federation_rec(federation: ?*slurm.db.Federation, free_it: bool) void;
pub extern fn slurmdb_init_instance_rec(instance: ?*slurm.db.Instance) void;
pub extern fn slurmdb_init_qos_rec(qos: ?*slurm.db.QoS, free_it: bool, init_val: u32) void;
pub extern fn slurmdb_init_res_rec(res: ?*slurm.db.Resource, free_it: bool) void;
pub extern fn slurmdb_init_wckey_rec(wckey: ?*slurm.db.WCKey, free_it: bool) void;
pub extern fn slurmdb_init_add_assoc_cond(add_assoc: ?*slurm.db.Association.AddConditions, free_it: bool) void;
pub extern fn slurmdb_init_tres_cond(tres: ?*slurm.db.TrackableResource.Filter, free_it: bool) void;
pub extern fn slurmdb_init_cluster_cond(cluster: ?*slurm.db.Cluster.Filter, free_it: bool) void;
pub extern fn slurmdb_init_federation_cond(federation: ?*slurm.db.Federation.Filter, free_it: bool) void;
pub extern fn slurmdb_init_res_cond(cluster: ?*slurm.db.Resource.Filter, free_it: bool) void;
pub extern fn slurmdb_ping(rem_host: ?slurm.CStr) c_int;
pub extern fn slurmdb_get_hierarchical_sorted_assoc_list(assoc_list: ?*slurm.List(*anyopaque)) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_get_acct_hierarchical_rec_list(assoc_list: ?*slurm.List(*anyopaque)) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_tree_name_get(name: ?slurm.CStr, parent: ?slurm.CStr, tree_list: ?*slurm.List(*anyopaque)) ?slurm.CStr;
pub extern fn slurmdb_res_add(db_conn: ?*slurm.db.Connection, res_list: ?*slurm.List(*anyopaque)) c_int;
pub extern fn slurmdb_res_get(db_conn: ?*slurm.db.Connection, res_cond: ?*slurm.db.Resource.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_res_modify(db_conn: ?*slurm.db.Connection, res_cond: ?*slurm.db.Resource.Filter, res: ?*slurm.db.Resource) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_res_remove(db_conn: ?*slurm.db.Connection, res_cond: ?*slurm.db.Resource.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_qos_add(db_conn: ?*slurm.db.Connection, qos_list: ?*slurm.List(*anyopaque)) c_int;
pub extern fn slurmdb_qos_get(db_conn: ?*slurm.db.Connection, qos_cond: ?*slurm.db.QoS.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_qos_modify(db_conn: ?*slurm.db.Connection, qos_cond: ?*slurm.db.QoS.Filter, qos: ?*slurm.db.QoS) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_qos_remove(db_conn: ?*slurm.db.Connection, qos_cond: ?*slurm.db.QoS.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_tres_add(db_conn: ?*slurm.db.Connection, tres_list: ?*slurm.List(*anyopaque)) c_int;
pub extern fn slurmdb_tres_get(db_conn: ?*slurm.db.Connection, tres_cond: ?*slurm.db.TrackableResource.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_usage_get(db_conn: ?*slurm.db.Connection, in: ?*anyopaque, @"type": c_int, start: std.posix.time_t, end: std.posix.time_t) c_int;
pub extern fn slurmdb_usage_roll(db_conn: ?*slurm.db.Connection, sent_start: std.posix.time_t, sent_end: std.posix.time_t, archive_data: u16, rollup_stats_list_in: *?*slurm.List(*anyopaque)) c_int;
pub extern fn slurmdb_users_add(db_conn: ?*slurm.db.Connection, user_list: ?*slurm.List(*anyopaque)) c_int;
pub extern fn slurmdb_users_add_cond(db_conn: ?*slurm.db.Connection, add_assoc: ?*slurm.db.Association.AddConditions, user: ?*slurm.db.User) ?slurm.CStr;
pub extern fn slurmdb_users_add_conn(db_conn: ?*slurm.db.Connection, user: ?*slurm.db.User, assoc_cond: ?*slurm.db.Association.Filter, assoc: ?*slurm.db.Association) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_users_get(db_conn: ?*slurm.db.Connection, user_cond: ?*slurm.db.User.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_users_modify(db_conn: ?*slurm.db.Connection, user_cond: ?*slurm.db.User.Filter, user: ?*slurm.db.User) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_users_remove(db_conn: ?*slurm.db.Connection, user_cond: ?*slurm.db.User.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_wckeys_add(db_conn: ?*slurm.db.Connection, wckey_list: ?*slurm.List(*anyopaque)) c_int;
pub extern fn slurmdb_wckeys_get(db_conn: ?*slurm.db.Connection, wckey_cond: ?*slurm.db.WCKey.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_wckeys_modify(db_conn: ?*slurm.db.Connection, wckey_cond: ?*slurm.db.WCKey.Filter, wckey: ?*slurm.db.WCKey) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_wckeys_remove(db_conn: ?*slurm.db.Connection, wckey_cond: ?*slurm.db.WCKey.Filter) ?*slurm.List(*anyopaque);
pub extern fn slurmdb_expand_job_stdio_fields(path: ?slurm.CStr, job: ?*slurm.db.Job) ?slurm.CStr;
pub extern fn slurmdb_expand_step_stdio_fields(path: ?slurm.CStr, step: ?*slurm.db.Step) ?slurm.CStr;
